Updated README and added CONTRIBUTING.md file
ARMmbed/mbed-os-example-atecc608a pull request #51
Opened 2020-09-16 14:32 UTC by harmut01

## Summary of changes
Fixes: #33 
Created CONTRIBUTING.md
Added license information to README.md

## Impact of changes

None
## Migration actions required

None.
## Documentation

None.
## Pull request type

[x] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
[] Feature update (New feature / Functionality change / New API)
[] Major update (Breaking change E.g. Return code change / API behaviour change)

## Test results

[X] No Tests required for this change (E.g docs only update)
[] Covered by existing mbed-os tests (Greentea or Unittest)
[] Tests / results supplied as part of this PR
## Reviewers
@mbed-os-core

2020-09-16 15:48 UTC, LDong-Arm approved these changes

2020-09-16 15:51 UTC, LDong-Arm requested changes
Thanks @harmut01, it looks good apart from a small suggestion

2020-09-16 15:51 UTC, LDong-Arm commented on README.md
> +This project contains code from other projects. The original license text is included in those source files. They must comply with our [license guide](https://os.mbed.com/docs/mbed-os/v6.2/contributi
```suggestion
This project contains code from other projects. The original license text is included in those source files. They must comply with our [license guide](https://os.mbed.com/docs/mbed-os/latest/contributing/license.html)
```
The link is always redirected to the latest version.

2020-09-17 17:26 UTC, evedon approved these changes

2020-09-17 17:27 UTC, merged